bin\PathTracingLab1.exe: 		lib\Main.o
	g++ -o bin\PathTracingLab1.exe lib\Main.o

lib\Main.o:						src\Main.cpp
	g++ -o lib\Main.o -c src\Main.cpp

clean:
	rm bin\PathTracingLab1.exe lib\Main.o

run:
	bin\PathTracingLab1.exe